//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallSwitch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WallSwitch.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (active).
        /// </summary>
        internal static string ActiveTheme {
            get {
                return ResourceManager.GetString("ActiveTheme", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Switch.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WallSwitch.
        /// </summary>
        internal static string AppNameIdent {
            get {
                return ResourceManager.GetString("AppNameIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Switch - Version {0}.
        /// </summary>
        internal static string AppNameVersion {
            get {
                return ResourceManager.GetString("AppNameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        internal static string BackOpacityPercent {
            get {
                return ResourceManager.GetString("BackOpacityPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause.
        /// </summary>
        internal static string Button_Pause {
            get {
                return ResourceManager.GetString("Button_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un&amp;pause.
        /// </summary>
        internal static string Button_Unpause {
            get {
                return ResourceManager.GetString("Button_Unpause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Char_Cr {
            get {
                return ResourceManager.GetString("Char_Cr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Char_Lf {
            get {
                return ResourceManager.GetString("Char_Lf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string Char_Space {
            get {
                return ResourceManager.GetString("Char_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        internal static string Char_Tab {
            get {
                return ResourceManager.GetString("Char_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        internal static string CollageFadeRatioPercent {
            get {
                return ResourceManager.GetString("CollageFadeRatioPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made changes to this theme. Do you want to save changes before changing?.
        /// </summary>
        internal static string Confirm_ChangeDirtyTheme {
            get {
                return ResourceManager.GetString("Confirm_ChangeDirtyTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        internal static string Confirm_ChangeDirtyTheme_Caption {
            get {
                return ResourceManager.GetString("Confirm_ChangeDirtyTheme_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the theme &apos;{0}&apos;?.
        /// </summary>
        internal static string Confirm_DeleteTheme {
            get {
                return ResourceManager.GetString("Confirm_DeleteTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Theme?.
        /// </summary>
        internal static string Confirm_DeleteTheme_Caption {
            get {
                return ResourceManager.GetString("Confirm_DeleteTheme_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made changes to this theme. Do you want to save changes before hiding the window?.
        /// </summary>
        internal static string Confirm_HideWindowDirtyTheme {
            get {
                return ResourceManager.GetString("Confirm_HideWindowDirtyTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        internal static string Confirm_HideWindowDirtyThemeCaption {
            get {
                return ResourceManager.GetString("Confirm_HideWindowDirtyThemeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultTheme {
            get {
                return ResourceManager.GetString("DefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete the last theme in the list. There must be at least one theme present..
        /// </summary>
        internal static string Error_CantDeleteLastTheme {
            get {
                return ResourceManager.GetString("Error_CantDeleteLastTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error_Caption {
            get {
                return ResourceManager.GetString("Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Error_Content {
            get {
                return ResourceManager.GetString("Error_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///{1}.
        /// </summary>
        internal static string Error_ContentEx {
            get {
                return ResourceManager.GetString("Error_ContentEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory has been moved or deleted..
        /// </summary>
        internal static string Error_DirectoryMissing {
            get {
                return ResourceManager.GetString("Error_DirectoryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is already present in the list..
        /// </summary>
        internal static string Error_DuplicateFolder {
            get {
                return ResourceManager.GetString("Error_DuplicateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image file has been moved or deleted..
        /// </summary>
        internal static string Error_ImageFileMissing {
            get {
                return ResourceManager.GetString("Error_ImageFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid update frequency..
        /// </summary>
        internal static string Error_InvalidFeedUpdateFreq {
            get {
                return ResourceManager.GetString("Error_InvalidFeedUpdateFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid update period..
        /// </summary>
        internal static string Error_InvalidFeedUpdatePeriod {
            get {
                return ResourceManager.GetString("Error_InvalidFeedUpdatePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid feed path or URL..
        /// </summary>
        internal static string Error_InvalidFeedUrl {
            get {
                return ResourceManager.GetString("Error_InvalidFeedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid maximum image scale..
        /// </summary>
        internal static string Error_InvalidMaxImageScale {
            get {
                return ResourceManager.GetString("Error_InvalidMaxImageScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid frequency.
        /// </summary>
        internal static string Error_InvalidThemeFreq {
            get {
                return ResourceManager.GetString("Error_InvalidThemeFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image order.
        /// </summary>
        internal static string Error_InvalidThemeOrder {
            get {
                return ResourceManager.GetString("Error_InvalidThemeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid period.
        /// </summary>
        internal static string Error_InvalidThemePeriod {
            get {
                return ResourceManager.GetString("Error_InvalidThemePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when loading the settings..
        /// </summary>
        internal static string Error_LoadSettings {
            get {
                return ResourceManager.GetString("Error_LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when loading a theme. It may be lost..
        /// </summary>
        internal static string Error_LoadTheme {
            get {
                return ResourceManager.GetString("Error_LoadTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This location does not exist..
        /// </summary>
        internal static string Error_LocationMissing {
            get {
                return ResourceManager.GetString("Error_LocationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum image scale must be greater than zero..
        /// </summary>
        internal static string Error_NegativeMaxImageScale {
            get {
                return ResourceManager.GetString("Error_NegativeMaxImageScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when creating a new theme..
        /// </summary>
        internal static string Error_NewTheme {
            get {
                return ResourceManager.GetString("Error_NewTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when renaming the theme..
        /// </summary>
        internal static string Error_RenameTheme {
            get {
                return ResourceManager.GetString("Error_RenameTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when saving the settings..
        /// </summary>
        internal static string Error_SaveSettings {
            get {
                return ResourceManager.GetString("Error_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update frequency cannot be less than 15 seconds..
        /// </summary>
        internal static string Error_ShortUpdateInterval {
            get {
                return ResourceManager.GetString("Error_ShortUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when showing the about dialog..
        /// </summary>
        internal static string Exception_AboutDialog {
            get {
                return ResourceManager.GetString("Exception_AboutDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when adding an image file to the list..
        /// </summary>
        internal static string Exception_AddFile {
            get {
                return ResourceManager.GetString("Exception_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when adding a folder to the list..
        /// </summary>
        internal static string Exception_AddFolder {
            get {
                return ResourceManager.GetString("Exception_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred..
        /// </summary>
        internal static string Exception_Generic {
            get {
                return ResourceManager.GetString("Exception_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when detecting the application version.
        ///
        ///{0}.
        /// </summary>
        internal static string Exception_GetAppVersion {
            get {
                return ResourceManager.GetString("Exception_GetAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get icon for location &apos;{0}&apos;.
        /// </summary>
        internal static string Exception_GetIcon {
            get {
                return ResourceManager.GetString("Exception_GetIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when initializing the settings: {0}.
        /// </summary>
        internal static string Exception_InitSettings {
            get {
                return ResourceManager.GetString("Exception_InitSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid background opacity value..
        /// </summary>
        internal static string Exception_LoadTheme_InvalidBackOpacity {
            get {
                return ResourceManager.GetString("Exception_LoadTheme_InvalidBackOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid theme frequency..
        /// </summary>
        internal static string Exception_LoadTheme_InvalidFrequency {
            get {
                return ResourceManager.GetString("Exception_LoadTheme_InvalidFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &apos;maintain aspect ratio&apos; flag..
        /// </summary>
        internal static string Exception_LoadTheme_InvalidMaintainAspectRatio {
            get {
                return ResourceManager.GetString("Exception_LoadTheme_InvalidMaintainAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid theme period..
        /// </summary>
        internal static string Exception_LoadTheme_InvalidPeriod {
            get {
                return ResourceManager.GetString("Exception_LoadTheme_InvalidPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid separate monitors flag..
        /// </summary>
        internal static string Exception_LoadTheme_InvalidSeparateMonitors {
            get {
                return ResourceManager.GetString("Exception_LoadTheme_InvalidSeparateMonitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme does not have a name..
        /// </summary>
        internal static string Exception_NoThemeName {
            get {
                return ResourceManager.GetString("Exception_NoThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when showing the options dialog..
        /// </summary>
        internal static string Exception_OptionsDialog {
            get {
                return ResourceManager.GetString("Exception_OptionsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current theme could be selected..
        /// </summary>
        internal static string Exception_SelectNewCurrentTheme {
            get {
                return ResourceManager.GetString("Exception_SelectNewCurrentTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when signaling to switch wallpapers..
        /// </summary>
        internal static string Exception_SwitchNow {
            get {
                return ResourceManager.GetString("Exception_SwitchNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when signaling to switch wallpapers..
        /// </summary>
        internal static string Exception_SwitchNowTray {
            get {
                return ResourceManager.GetString("Exception_SwitchNowTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when switching to the previous wallpaper..
        /// </summary>
        internal static string Exception_SwitchPrev {
            get {
                return ResourceManager.GetString("Exception_SwitchPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when switching to the previous wallpaper..
        /// </summary>
        internal static string Exception_SwitchPrevTray {
            get {
                return ResourceManager.GetString("Exception_SwitchPrevTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred within the background monitor thread: {0}.
        /// </summary>
        internal static string Exception_SwitchThread {
            get {
                return ResourceManager.GetString("Exception_SwitchThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background opacity must be between 0 and 100..
        /// </summary>
        internal static string Exception_Theme_BackOpacity {
            get {
                return ResourceManager.GetString("Exception_Theme_BackOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size must be between 1 and 100..
        /// </summary>
        internal static string Exception_Theme_ImageSize {
            get {
                return ResourceManager.GetString("Exception_Theme_ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme frequency must be greater than zero..
        /// </summary>
        internal static string Exception_ThemeFreqOutOfRange {
            get {
                return ResourceManager.GetString("Exception_ThemeFreqOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pixels.
        /// </summary>
        internal static string FeatherWidth {
            get {
                return ResourceManager.GetString("FeatherWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        internal static string HotKey_Alt {
            get {
                return ResourceManager.GetString("HotKey_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        internal static string HotKey_Control {
            get {
                return ResourceManager.GetString("HotKey_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  + .
        /// </summary>
        internal static string HotKey_Delim {
            get {
                return ResourceManager.GetString("HotKey_Delim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string HotKey_Shift {
            get {
                return ResourceManager.GetString("HotKey_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageCache.
        /// </summary>
        internal static string ImageCacheDir {
            get {
                return ResourceManager.GetString("ImageCacheDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files ({0})|{0}|All Files (*.*)|*.*.
        /// </summary>
        internal static string ImageFileFilter {
            get {
                return ResourceManager.GetString("ImageFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        internal static string ImageSizePercent {
            get {
                return ResourceManager.GetString("ImageSizePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WallSwitch.log.
        /// </summary>
        internal static string LogFile {
            get {
                return ResourceManager.GetString("LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the new theme:.
        /// </summary>
        internal static string NewThemePrompt {
            get {
                return ResourceManager.GetString("NewThemePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Theme.
        /// </summary>
        internal static string NewThemeTitle {
            get {
                return ResourceManager.GetString("NewThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (next refresh).
        /// </summary>
        internal static string NextUpdateNow {
            get {
                return ResourceManager.GetString("NextUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper history has been cleared..
        /// </summary>
        internal static string Notify_HistoryCleared {
            get {
                return ResourceManager.GetString("Notify_HistoryCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Notify_Paused {
            get {
                return ResourceManager.GetString("Notify_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WallSwitch.
        /// </summary>
        internal static string Notify_Title {
            get {
                return ResourceManager.GetString("Notify_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaused.
        /// </summary>
        internal static string Notify_Unpaused {
            get {
                return ResourceManager.GetString("Notify_Unpaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WallSwitch.
        /// </summary>
        internal static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new name for the theme:.
        /// </summary>
        internal static string RenameThemePrompt {
            get {
                return ResourceManager.GetString("RenameThemePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Theme.
        /// </summary>
        internal static string RenameThemeTitle {
            get {
                return ResourceManager.GetString("RenameThemeTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon RSS {
            get {
                object obj = ResourceManager.GetObject("RSS", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WallSwitch.
        /// </summary>
        internal static string SettingsDir {
            get {
                return ResourceManager.GetString("SettingsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.xml.
        /// </summary>
        internal static string SettingsFileName {
            get {
                return ResourceManager.GetString("SettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of WallSwitch is now available to download.
        ///
        ///Click here to be taken to the download page..
        /// </summary>
        internal static string UpdateAvailableBalloonText {
            get {
                return ResourceManager.GetString("UpdateAvailableBalloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when checking for updates..
        /// </summary>
        internal static string UpdateCheckFailedBalloonText {
            get {
                return ResourceManager.GetString("UpdateCheckFailedBalloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WallSwitch is up to date..
        /// </summary>
        internal static string UpdateNotAvailableBalloonText {
            get {
                return ResourceManager.GetString("UpdateNotAvailableBalloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://wallswitch.codeplex.com/project/feeds/rss?ProjectRSSFeed=codeplex%3a%2f%2frelease%2fwallswitch.
        /// </summary>
        internal static string UpdateRssUrl {
            get {
                return ResourceManager.GetString("UpdateRssUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper.bmp.
        /// </summary>
        internal static string WallpaperFileName {
            get {
                return ResourceManager.GetString("WallpaperFileName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap WallSwitch {
            get {
                object obj = ResourceManager.GetObject("WallSwitch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
